on:
  push:
    branches:
      - main
  pull_request:

env:
  ACTIVATE: source /localdisk/work/rscohn1/github-runners/venv/distributed-ranges/bin/activate
  SPHINXOPTS: -q -W

jobs:
  checks:
    runs-on: dds-base
    steps:
    - uses: actions/checkout@v3
    - name: Checks
      run: |
        ${ACTIVATE}
        pre-commit run --all
    - name: Build doc
      run: |
        ${ACTIVATE}
        make -C doc/spec html

  examples:
    strategy:
      matrix:
        include:
        - cxx: clang++
          cc: clang
        - cxx: g++-10
          cc: gcc-10
        - cxx: icpx
          cc: icx
    name: Build/test examples (${{ matrix.cxx }})
    runs-on: dds-base
    env:
      CXX: ${{ matrix.cxx }}
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        source /opt/intel/oneapi/setvars.sh
        mkdir build
        cd build
        cmake ..
    - name: build
      run: |
        cd build
        make -j all
    - name: test
      run: |
        cd build
        make test

  publish:
    needs: [checks, examples]
    runs-on: dds-base
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v3
    - name: Checkout gh-pages
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
    - name: Build docs
      run: |
        ${ACTIVATE}
        make -C doc/spec html
    - name: Publish to github pages
      run: |
        ${ACTIVATE}
        rm -rf gh-pages/*
        touch gh-pages/.nojekyll

        cp -r doc/spec/build/html gh-pages/spec
        cp -r doc/spec/build/doxygen-html gh-pages/doxygen

        cd gh-pages
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        # Ignore errors because no updates returns an error status.
        git commit --reset-author --amend -m "Update from github actions"
        git push --force origin gh-pages
