on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * Sun'

jobs:
  coverity:
    runs-on: dds-base
    env:
      CXX: g++-10
    steps:
    - uses: actions/checkout@v3

    - name: Configure coverity
      run: |
        /opt/coverity/analysis/bin/cov-configure --config coverity.xml --compiler ${CXX} --comptype gcc --template

    - name: Build with coverity
      run: |
        source /opt/intel/oneapi/setvars.sh
        cmake -B build
        /opt/coverity/analysis/bin/cov-build --config coverity.xml --dir idir make -C build all

    - name: Analyze and upload results
      run: |
        /opt/coverity/analysis/bin/cov-analyze --dir idir --concurrency --security --rule --enable-constraint-fpp --enable-fnptr --enable-virtual
        echo '${{ secrets.COVERITY_AUTH }}' > auth.key
        chmod 600 auth.key
        /opt/coverity/analysis/bin/cov-commit-defects --dir idir --stream "DR main" --url https://coverityent.devtools.intel.com/prod7 --auth-key-file auth.key
        rm auth.key
