# SPDX-FileCopyrightText: Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * Sun'

jobs:
  bdba:
    runs-on: dds-base
    env:
      CXX: g++-12
      SCAN_NAME: DistributedRanges-${{ github.shaA }}
    steps:
    - uses: actions/checkout@v3
    - name: Build & test
      run: |
        source /opt/intel/oneapi/setvars.sh
        cmake -B build
        make -j -C build/examples/cpu all test
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: python -m pip install -i https://af01p-igk.devtools.intel.com/artifactory/api/pypi/dtt-pypi-igk-local/simple bdba
    - name: Scan
      run: |
        tar -cvzf bdba/dr-bdba.tgz --exclude="*.o" build/examples/cpu
        bdba upload --scan-name ${SCAN_NAME}} --products-json-path bdba/file.json --path bdba/dr-bdba.tgz --key ${{ secrets.BDBA_KEY }}
        bdba override --products-json-path bdba/file.json -c bdba/bdba.yaml --key ${{ secrets.BDBA_KEY }}
        bdba pdf-report --products-json-path bdba/file.json --key ${{ secrets.BDBA_KEY }}
    - uses: actions/upload-artifact@v3
      with:
        name: bdba-scan
        path: dr-bdba.tgz.pdf

  coverity:
    runs-on: dds-base
    env:
      CXX: g++-10
    steps:
    - uses: actions/checkout@v3

    - name: Configure coverity
      run: |
        /opt/coverity/analysis/bin/cov-configure --config coverity.xml --compiler ${CXX} --comptype gcc --template

    - name: Build with coverity
      run: |
        source /opt/intel/oneapi/setvars.sh
        cmake -B build
        /opt/coverity/analysis/bin/cov-build --config coverity.xml --dir idir make -C build all

    - name: Analyze and upload results
      run: |
        /opt/coverity/analysis/bin/cov-analyze --dir idir --concurrency --security --rule --enable-constraint-fpp --enable-fnptr --enable-virtual
        echo '${{ secrets.COVERITY_AUTH }}' > auth.key
        chmod 600 auth.key
        /opt/coverity/analysis/bin/cov-commit-defects --dir idir --stream "DR main" --url https://coverityent.devtools.intel.com/prod7 --auth-key-file auth.key
        rm auth.key

  malware:
    runs-on: dds-base
    env:
      CXX: g++-12
    steps:
    - uses: actions/checkout@v3
    - name: Build & test
      run: |
        source /opt/intel/oneapi/setvars.sh
        cmake -B build
        make -j -C build/examples/cpu all test
    - name: Scan
      run: |
        cd build/examples/cpu
        uvscan --RPTOBJECTS --RECURSIVE --UNZIP --HTML=scan-report.html --LOUD --SUMMARY --ANALYZE --PANALYZE .
    - uses: actions/upload-artifact@v3
      with:
        name: malware-scan
        path: build/examples/cpu/scan-report.html

  fuzzer:
    runs-on: dds-base
    env:
      CXX: clang++
    steps:
    - uses: actions/checkout@v3
    - name: Build & test
      run: |
        source /opt/intel/oneapi/setvars.sh
        cmake -B build
        make -j -C build/fuzz/cpu
        build/fuzz/cpu/cpu-fuzz -max_len=16 -runs=100000000 2> fuzz.txt
    - uses: actions/upload-artifact@v3
      with:
        name: fuzzer
        path: fuzz.txt
